name: deploy Emmanuel dashboard
on: push

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: CheckOut
      uses: actions/checkout@v5.0.0

    - name: Setup SSH
      run: | 
         echo "${{ secrets.SSH_KEY }}" > key.pem
         chmod 600 key.pem

    - name: Authenticate and Deploy To EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.USER_NAME }}@${{ secrets.HOST }} << 'EOF'
        
          sudo apt update
          sudo apt install nginx -y
          sudo systemctl enable nginx
          sudo systemctl restart nginx
          sudo git clone https://github.com/frankisinfotech/merchantPay.git
          ls -la
          sudo cp -r /home/${{ secrets.USER_NAME }}/merchantPay/* /var/www/html
        EOF
