name: Emmatest

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check version
        run: hostnamectl

      - name: printwd
        run: pwd

      - name: who are you
        run: whoami

